all:

	gcc -o hello.exe hello.c

clean:
	rm -f hello.exe *.i *.s *.o


#cpp -o hello.i hello.c
#gcc -S -o hello.s hello.i
#as -o hello.o hello.s
#ld -o hello.exe \
#	-o hello.exe \
#	"c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../crt2.o" "c:/mingw/bin/../lib/gcc/mingw32/4.8.1/crtbegin.o" \
#	"-Lc:/mingw/bin/../lib/gcc/mingw32/4.8.1" "-Lc:/mingw/bin/../lib/gcc" \
#	"-Lc:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/lib" \
#	"-Lc:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../.." hello.o -lmingw32 -lgcc -lgcc_eh \
#	-lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh \
#	-lmoldname -lmingwex -lmsvcrt "c:/mingw/bin/../lib/gcc/mingw32/4.8.1/crtend.o"
#echo "Success!"